version: '2'
services:
  web:
    build: ./core/web
    # image: nginx:latest
    env_file:
      - ../.env
    environment:
      - "VIRTUAL_HOST=${WEB_HOST},www.${WEB_HOST},${APP_NAME}.dev2bit.com"
    volumes:
      - ./core/web/nginx.conf:/etc/nginx/nginx.conf
      - ./core/web/site.conf:/etc/nginx/conf.d/default.conf
      - /tmp/cache:/var/lib/nginx/cache
      - ../src:/var/www/html/
    depends_on:
      - script
    links:
      - script:script
  script:
    build: ./core/script
    working_dir: /var/www/html/
    env_file:
      - ../.env
    environment:
      - "VIRTUAL_HOST=script.${WEB_HOST}"
    volumes:
      - ./core/script/default.conf:/usr/local/etc/php-fpm.d/default.conf
      - ./core/script/php.ini:/usr/local/etc/php/php.ini
      - /tmp/html:/var/lib/nginx/cache
      - ../src:/var/www/html
  dev:
    build: ./core/dev/
    env_file:
      - ../.env
    volumes:
      - ./core/dev/run.d:/run.d
      - ../src:/var/www/html/
      - ../:/var/project
networks:
  default:
    external:
      name: "$NETWORK"
