version: '2'
services:
  script:
    depends_on:
      - db
    links:
      - db:db_host
  db:
    build: ./core/db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - db_data:/var/lib/mysql
  dev:
    links:
      - db:db_host
volumes:
  db_data:
